### ISSUE TITLE
Ubuntu 20.04 - openjdk-8 installs openjdk-11

### ISSUE THREAD

**Issue by kingsleyadam** [geerlingguy/ansible-role-java#111]
When I install `openjdk-8-jre-headless` and `openjdk-8-jdk-headless` it installs both openjdk8 and openjdk11 due to a dependency in `ca-certificates-java` which relies on `default-jre-headless`

My playbook.

```
- hosts: all
  become: true
  roles:
    - geerlingguy.java
  vars:
    java_packages:
      - openjdk-8-jre-headless
      - openjdk-8-jdk-headless
    java_home: "/usr/lib/jvm/java-8-openjdk-amd64"
```

What gets installed

```
$ apt list --installed | grep openjdk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openjdk-11-jre-headless/focal-updates,focal-security,now 11.0.10+9-0ubuntu1~20.04 amd64 [installed,automatic]
openjdk-11-jre/focal-updates,focal-security,now 11.0.10+9-0ubuntu1~20.04 amd64 [installed,automatic]
openjdk-8-jdk-headless/focal-updates,focal-security,now 8u282-b08-0ubuntu1~20.04 amd64 [installed]
openjdk-8-jre-headless/focal-updates,focal-security,now 8u282-b08-0ubuntu1~20.04 amd64 [installed]
```

I'm wondering if this can be address in this role itself.

I can set the alternatives to default to the correct Java, after the fact. Ideally OpenJDK-11 isn't installed at all on my server.

```
- name: Set the correct version of java
  alternatives:
    name: java
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
```
By default, it'll mark openjdk-11 as the default. Using this role with this config out-of-the-box is essentially broken on Ubuntu 20.04 for anyone using `java` command.
```
sudo update-alternatives --config java
There are 2 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
  2            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
```

Here's the dependency tree:
```
aptitude why openjdk-11-jre-headless
i   openjdk-8-jre-headless Depends ca-certificates-java
i A ca-certificates-java   Depends default-jre-headless | java8-runtime-headless
i A default-jre-headless   Depends openjdk-11-jre-headless
```
