### ISSUE TITLE
For people wanting jps support

### ISSUE THREAD

**Issue by anuraagvaidya** [geerlingguy/ansible-role-java#112]
I was wanting to use `jps` on openJDK for RHEL, here's what I did.

Use `java-1.8.0-openjdk-devel` variant as below.

```
- role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk-devel
```
Change the version as required.
