### ISSUE TITLE
Feature suggestion: add root certificates to truststore

### ISSUE THREAD

**Issue by cubistico** [geerlingguy/ansible-role-java#135]
We need to add our own root certifications to the truststore. To do so, we install Java, then use these tasks:
````
  tasks:
    - name: Copy root certificate to remote
      ansible.builtin.copy:
        src: files/mycert.pem
        dest: /tmp/mycert.pem
      
    - name: Install root certificate in Java truststores 
      community.general.java_cert:
        cert_path: /tmp/mycert.pem 
        cert_alias: mycert
        # this path is linked to both OpenJDK versions, so should work for all
        keystore_path: /etc/ssl/certs/java/cacerts
        keystore_pass: changeit
        state: present
        trust_cacert: true
```
It would be very handy if the java role had an option to add root certificates.
