### ISSUE TITLE
no java packages installed on Oracle Linux

### ISSUE THREAD

**Issue by juxbru** [geerlingguy/ansible-role-java#145]
Hello
Thanks for this role, it is very helpful.
I stumbled upon the following problem:
My system: Oracle Linux 8.8 and 9.3
I use the role like this:
```
ansible.builtin.include_role:
  name: geerlingguy.java
vars:
  java_packages:
    - java-1.8.0-openjdk
    - java-11-openjdk
```

But it was not installed on my Oracle Linux server (on Redhat systems it worked perfectly)
I then saw that the tasks/main.yml contains the following lines:
```
# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution_file_variety == 'RedHat'
```

For Oracle Linux, however, "ansible_distribution_file_variety" is "OracleLinux". As a hotfix I simply passed "ansible_distribution_file_variety: 'RedHat'" to the role but I think this can only be a quickfix.

Have I overlooked something when using the role or is the condition really missing for the package installation to work on Oracle Linux?
