### ISSUE TITLE
No JDK only JRE

### ISSUE THREAD

**Issue by kjayamit** [geerlingguy/ansible-role-java#18]
Hi, I have tried this one Centos 7. This installs only JRE, the lib folder which includes "tools.jar" (for eg) is missing. Only after installing java_1.8_-devel\* it brings in the other things. Thanks !

**Comment by fiunchinho** [comment]
Facing similar problems here :/

**Comment by billoneil** [comment]
I think this should be working as expected just append `-devel` if you want the JDK as well.

**Comment by kjenney** [comment]
I just verified that adding -devel to the java_packages does include tools.jar:

```
- hosts: still
  remote_user: root
  become: yes
  become_method: sudo
  gather_facts: yes
  vars:
    java_packages:
      - java-1.7.0-openjdk-devel
  roles:
    - ansible-role-java
```
