### ISSUE TITLE
Failed to fetch - 400 Bad Request

### ISSUE THREAD

**Issue by Rade333** [geerlingguy/ansible-role-java#19]
Hey,

I recently started randomly getting errors from the apt tasks in some different roles (java, mysql, php). Here is an example output from the task "Ensure Java is installed": http://pastebin.com/Sxd0Ye5G

When I say randomly I mean that if try provisioning multiple times, the failing task is randomly some of the apt tasks in the different roles. And then eventually, after many tries, they all pass.

If I ssh into the vagrant machine and try manually running the failed command (in this case `/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'openjdk-8-jdk'`) it runs successfully.

I don't actually think that this is an issue with your repos per se, but I wanted to ask if you might have encountered anything similar? I had trouble finding any solutions from Google.

**Comment by Rade333** [comment]
I think I found the solution!

Based on this post http://askubuntu.com/a/37754 I added the apt mirrors list in the provision playbook pre tasks, like so:

provision.yml
```
---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: Add apt mirrors into sources list
      apt_repository: repo='{{ item }}' state=present
      with_items:
        - deb mirror://mirrors.ubuntu.com/mirrors.txt xenial main restricted universe multiverse
        - deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-updates main restricted universe multiverse
        - deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-backports main restricted universe multiverse
        - deb mirror://mirrors.ubuntu.com/mirrors.txt xenial-security main restricted universe multiverse
```

Now the provisioning works smoothly and I don't get the errors anymore.
