### ISSUE TITLE
Oracle JDK not supported

### ISSUE THREAD

**Issue by netsensei** [geerlingguy/ansible-role-java#42]
I was trying to provision Oracle JDK instead of Open JDK with this role. But this gives me an error.

play.yml:

````
tasks:
    - name: Installing repo for Java 8 in Ubuntu
      become: true
      apt_repository: repo='ppa:webupd8team/java'

roles:
  - { role: geerlingguy.java  }
````

group_vars.yml

````
java_packages:
  - oracle-java8-installer
  - ca-certificates
  - oracle-java8-set-default
````

But this will fail with an error because the license this package presents, cannot be accepted in a non-interactive shell. In order to accomplish this, you need to add this extra task in the role:

main.yml

````
- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
````
