### ISSUE TITLE
Debian 8 Jessie - Java Version 8

### ISSUE THREAD

**Issue by DylanUnderwood** [geerlingguy/ansible-role-java#50]
Can you include Java 8 from backport so we can use Solr 6?

**Comment by geerlingguy** [comment]
@DylanUnderwood - For this particular role, I'm sticking with the system default packages—but it should be easy enough to shim in Java 8 whatever OS you're on. See my example from my Solr role (file: https://github.com/geerlingguy/ansible-role-solr/blob/master/tests/test-solr-6.yml#L11-L29), working example (at least I should think it would work!):

```yaml
- hosts: solr
  become: yes

  vars:
      java_packages:
          - openjdk-8-jdk

  pre_tasks:
    - name: Enable Backports repository.
      apt_repository:
        repo: 'deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main'
        state: present
        filename: "{{ ansible_distribution_release }}_backports"

    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600

  roles:
    - geerlingguy.java
    - geerlingguy.solr
```
