### ISSUE TITLE
install java 8 on ubuntu/trusty64 

### ISSUE THREAD

**Issue by altfatterz** [geerlingguy/ansible-role-java#54]
I am using the `ubuntu/trusty64` box with the following playbook (as described in the instructions)

```
---
- hosts: spring-boot-ansible
  become: yes
  gather_facts: yes

  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
```

but the `ansible-playbook install-with-role.yml --ask-pass` gives me

```
...
TASK [geerlingguy.java : Ensure Java is installed.] ******************************************************************************
failed: [spring-boot-ansible] (item=[u'openjdk-8-jdk']) => {"failed": true, "item": ["openjdk-8-jdk"], "msg": "No package matching 'openjdk-8-jdk' is available"}
	to retry, use: --limit @/Users/zoal/projects/study-vagrant-and-ansible/spring-boot-ansible/ansible/install-with-role.retry
...
```

What do I do wrong? How can I install java 8 on `ubuntu/trusty64` with this role?

Thanks.

**Comment by arshdeeptinna** [comment]
You will need to create a new block with same host and move roles under that. The way you have it setup now runs the roles first and then run tasks that you outline. 

```
- hosts: spring-boot-ansible
  become: yes
  gather_facts: yes

  tasks:
    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'
- hosts: spring-boot-ansible
  become: yes
  gather_facts: yes

  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'Debian'"
      java_packages:
        - openjdk-8-jdk
```
