### ISSUE TITLE
Conditional check for ansible_distribution fails

### ISSUE THREAD

**Issue by cruno91** [geerlingguy/ansible-role-java#58]
I'm getting an error about the OS checking in main.yml:

```
TASK [geerlingguy.java : Include OS-specific variables.] *****************************************************************
task path: geerlingguy.java/tasks/main.yml:2
fatal: [xxx.xxx.xx.x]: FAILED! => {
    "msg": "The conditional check 'ansible_distribution != 'Ubuntu' or ansible_distribution != 'Fedora'' failed. The error was: error while evaluating conditional (ansible_distribution != 'Ubuntu' or ansible_distribution != 'Fedora'): 'ansible_distribution' is undefined\n\nThe error appears to have been in 'geerlingguy.java/tasks/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Include OS-specific variables.\n  ^ here\n" 
}
```
Perhaps the way I'm using this for an Ubuntu 16.04.03 server is incorrect?
In my site.yml:
```
  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
```

**Comment by cruno91** [comment]
It looks like I was indeed using this incorrectly, but because I had gather_facts: false in my play to install python.  Updated play here (still not working 100% yet):
```
---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install Pythonn 2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  roles:
    - role: geerlingguy.java
      java_packages:
        - openjdk-8-jdk
```

**Comment by cruno91** [comment]
Fully working:
```
---
- hosts: all
  become: true
  roles:
    - geerlingguy.java
```
