### ISSUE TITLE
Ubuntu bionic not supported

### ISSUE THREAD

**Issue by abentley** [geerlingguy/ansible-role-java#61]
Running under Packer, I get this error.
```
    amazon-ebs: TASK [geerlingguy.java : Include version-specific variables for Debian.] *******
    amazon-ebs: fatal: [default]: FAILED! => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "message": "Could not find or access 'Ubuntu-18.yml'\nSearched in:\n\t/home/ubuntu/.ansible/roles/geerlingguy.java/vars/Ubuntu-18.yml\n\t/home/ubuntu/.ansible/roles/geerlingguy.java/Ubuntu-18.yml\n\t/home/ubuntu/.ansible/roles/geerlingguy.java/tasks/vars/Ubuntu-18.yml\n\t/home/ubuntu/.ansible/roles/geerlingguy.java/tasks/Ubuntu-18.yml\n\t/home/ubuntu/big/jenkins/ansible/vars/Ubuntu-18.yml\n\t/home/ubuntu/big/jenkins/ansible/Ubuntu-18.yml"}
    amazon-ebs: 	to retry, use: --limit @/home/ubuntu/big/jenkins/ansible/playbook.retry
    amazon-ebs:

```
This is with role version 1.8.0
"bionic" is listed as supported on ansible-galaxy
