### ISSUE TITLE
Package Not Found on RHEL 7

### ISSUE THREAD

**Issue by baldwinjim** [geerlingguy/ansible-role-java#66]
Getting the flowing when I try to use the role to install Java 

    "results": [
        "No package matching 'java-1.8.0-openjdk' found available, installed or updated"
    ],
    "item": "java-1.8.0-openjdk",
    "rc": 126,

This is on RHEL 7 and when I do  a yum list on that server for the package I can see this:

java-1.8.0-openjdk.i686                                              1:1.8.0.171-8.b10.el7_5                                             rhel-7-server-rpms
java-1.8.0-openjdk.x86_64                                            1:1.8.0.171-8.b10.el7_5                                             rhel-7-server-rpms

My playbook looks like this:

```
---
- hosts: jenkins
  become: yes
  gather_facts: yes
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
```

Not sure what I am doing wrong.
