### ISSUE TITLE
AnsibleError exception while templating {{ java packages }}

### ISSUE THREAD

**Issue by wand3r3r** [geerlingguy/ansible-role-java#96]
I am trying to run this role in my playbook and no matter what I try I get the following error

`FAILED! => {"msg": "The conditional check 'java_packages is not defined' failed. The error was: An unhandled exception occurred while templating '{{ java_packages }}'.`

In my playbook, I've tried the following.
```
- hosts: <myhost>
  vars:
    java_packages:
      - java-1.8.0-openjdk
      - javapackages-tools
  tasks:
    - name: Install java
      include_role: geerlingguy.java
      vars:
        # attempt 1
        # java_packages: "{{ java_packages }}"
        # attempt 2
        # java_packages:
        #  - "{{ java_packages }}"
        # attempt 3
        java_packages:
         - java-1.8.0-openjdk
         - javapackages-tools
```
What is causing this error?
